# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('imagen1', models.ImageField(upload_to='media/Image')),
                ('imagen2', models.ImageField(upload_to='media/Image')),
                ('imagen3', models.ImageField(upload_to='media/Image')),
                ('imagen4', models.ImageField(upload_to='media/Image')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
