# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Telefono', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='shop_body',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shop_men',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='shop_body',
            name='Telefono',
            field=models.ManyToManyField(to='Shop.Contacto'),
        ),
        migrations.AddField(
            model_name='shop_men',
            name='Telefono',
            field=models.ManyToManyField(to='Shop.Contacto'),
        ),
    ]
